#!/usr/bin/env bash

usage() {
    echo "Usage: $0 [-l language] [-b basefile1] ... [-b basefilen]" \
         "gradebook1.zip gradebook2.zip gradebook3.zip ..." 1>&2
}

while getopts ":l:b:" o; do
    case "${o}" in
        l)
            l=${OPTARG}
            ;;
        b)
            basefiles+=("$OPTARG")
            ;;
        *)
            usage
            exit 1;
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "$l" ]; then
    l='c'
fi

MYDIR=$(dirname $0)
tempdir=$(mktemp -d)

if [ -z "$1" ]; then
    usage
    exit 2;
fi

for archive in $@
do
    if [[ "$archive" != *.zip ]]; then
        usage
        exit 3;
    elif [ ! -f "$archive" ]; then
        usage
        exit 4;
    fi

    unzip "$archive" -d "$tempdir"
done

echo 'Removing text submissions'
rm "$tempdir"/*_*_attempt_[1-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]-[0-2][0-9]-[0-5][0-9]-[0-5][0-9].txt

echo 'Replacing spaces in filenames with underscores'
for f in "$tempdir"/*\ *; do mv "$f" "${f// /_}"; done

echo 'Separating user submissions into individual directories'
for file in "$tempdir"/*
do
    filename=$(basename "$file")
    extension="${filename##*.}"
    filename="${filename%.*}"
    newdir="$tempdir/$filename.dir"

    mkdir "$newdir"

    if [ "$extension" == 'zip' ]; then
        unzip "$file" -d "$newdir"
        rm "$file"
    elif [ "$extension" == 'rar' ]; then
        unrar x "$file" "$newdir"
        rm "$file"
    elif [ "$extension" == 'tar' ]; then
        tar xvC "$newdir" -f "$file"
        rm "$file"
    elif [ "$extension" == '7z' ]; then
        7za x "$file" -o"$newdir"
        rm "$file"
    elif [ "$extension" == 'gz' ]; then
        tar xvzC "$newdir" -f "$file"
        rm "$file"
    elif [ "$extension" == 'doc' ] || 
         [ "$extension" == 'docx' ] || 
         [ "$extension" == 'pdf' ] ; then
        rm "$file"
    else
        mv "$file" "$newdir"
    fi
done

for basefile in "${basefiles[@]}"
do
    b+="-b $basefile "
done

find "$tempdir"/*/ -type f -exec grep -Iq . {} \; -and -print |
xargs -d "\n" "$MYDIR"/moss -l $l $b -d
